version: '3'

services:
  autonity:
    image: ghcr.io/autonity/autonity:latest
    command: >
      --datadir /autonity-chaindata
      --piccadilly
      --http
      --http.addr 0.0.0.0
      --http.api aut,eth,net,txpool,web3,admin
      --http.vhosts *
      --ws
      --ws.addr 0.0.0.0
      --ws.api aut,eth,net,txpool,web3,admin
      --nat extip:${EXTERNAL_IP}
    volumes:
      - ./autonity-chaindata:/autonity-chaindata
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
      - "6060:6060"
    stdin_open: true
    tty: true
    container_name: autonity
    restart: "no"
